version: 'v1'

networks:
  monitor-net:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:

services:
  nginx:
    image: nginx:alpine
    container_name: portfolio-site
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/config/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - monitor-net

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx-exporter
    command: -nginx.scrape-uri=http://nginx/status
    ports:
      - "9113:9113"
    depends_on:
      - nginx
    networks:
      - monitor-net
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: prometheus-2
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitor-net
    depends_on:
      - prometheus
